version: '3.2'
services:
  rails:
    build: ./order_service
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: order_service
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq
  db:
    image: postgres:12-alpine
    ports:
     - '5432:5432'
    environment:
      - POSTGRES_USE=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  geo:
    build: ./geolocation_service
    command: bash -c "bundle exec rails s -p 3003 -b '0.0.0.0'"
    container_name: geolocation_service
    ports:
      - 3003:3003
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
